name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        env:
          NUGET_KEY: ${{ secrets.PSGALLERY }}
        run: .\publish.ps1
        shell: pwsh